config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :likes
  end
  resources :comments
  root "static_pages#home"
  resources :users, except: [:new], path: "usuarios"
  get "/cadastro", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post

    def create
        @comment = Comment.new(comment_params)
        if @comment.save
            redirect_to post_path(@post)

        else
            redirect_to root_path

        end
    end

    private

        def comment_params
            params.permit(:user_id, :post_id, :content)
        end


        def find_post
            @post = Post.find(params[:post_id])
        end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post

    def create
        if !has_liked?
            @post.likes.create(user_id: current_user().id)
        end
        redirect_to post_path(@post)
    end


    private

    

        def has_liked?
            Like.where(user_id: current_user().id, post_id: params[:post_id]).exists?
        end

        def find_post
            @post = Post.find(params[:post_id])
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :impede_nao_logado, only: [:new]

	# GET /posts
	# GET /posts.json
	def index
		@posts = Post.all
	end

	# GET /posts/1
	# GET /posts/1.json
	def show
		@comments = Comment.all
	end

	# GET /posts/new
	def new
		@post = Post.new
	end

	# GET /posts/1/edit
	def edit
	end

	# POST /posts
	# POST /posts.json
	def create
		@post = Post.new(post_params)

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
				format.json { render :show, status: :created, location: @post }
			else
				format.html { render :new }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /posts/1
	# PATCH/PUT /posts/1.json
	def update
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
				format.json { render :show, status: :ok, location: @post }
			else
				format.html { render :edit }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /posts/1
	# DELETE /posts/1.json
	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_post
			@post = Post.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def post_params
			params.require(:post).permit(:title, :content, :user_id)
		end
		def impede_nao_logado
            if !logged_in?
                redirect_to root_path
            end
        end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :impede_logado, only: [:new]
    
    before_action :impede_nao_logado, only: [:destroy]
    
    
    def  new
    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end
    private
        def impede_nao_logado
            if !logged_in?
                redirect_to login_path
            end
        end

        def impede_logado
            if logged_in?
                redirect_to current_user
            end
        end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :impede_logado, only: [:home]
    
    
    def home
    end

    private
        def impede_logado
            if logged_in?
                redirect_to current_user
            end
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :impede_nao_logado, except: [:new, :create] 
    before_action :impede_logado, only: [:new]

    def new
        @user = User.new
    end

    def create
        @user =  User.new(user_params)

        if @user.save
            redirect_to login_path

        else
            render "new"
        end
    end

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @posts = Post.all
    end


    private

        def user_params
            params.require(:user).permit( :name, :email, :password, :password_confirmation)
        end

        def impede_nao_logado
            if !logged_in?
                redirect_to root_path
            end
        end
        
        def impede_logado
            if logged_in?
                redirect_to current_user
            end
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def find_post
        @post = Post.find(params[:post_id])
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end

    def logged_in? 
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginESenha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: :delete  %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<h1>vc deu um like<h1>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, :value => current_user().id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', root_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Likes</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= post.likes.length %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'Back', root_path %> 

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong><%= link_to "likes:", post_likes_path(@post),  method: :post %></strong>
  <%= @post.likes.length%>
</p>


<%= form_with(url: comments_path, method: :post, local: true) do |form| %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.hidden_field :post_id, value: @post.id  %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user().id  %>
  </div>

  <div class="actions">
    <%= form.submit "Add comment"%>
  </div>
<% end %>


<p>
  <strong>Comments: </strong>
</p>


<p>
  <table>
    <thead>
      <tr>
        <th>Content</th>
        <th>User</th>
        <th colspan="2"></th>
      </tr>
    </thead>


    <tbody>
      <% @comments.each do |comment| %>
        <%if comment.post == @post%>
          <tr>
            <td><%= comment.content %></td>
            <td><%= comment.user.name %></td>s
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>
</p>


<%= link_to 'Back', root_path %>

app/views/static_pages/home.html.erb
<h1>Bem vindo!<h1>
<h3><%=link_to "Cadastre-se", cadastro_path%> ou <%=link_to "log in", login_path%><h3>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

    <div class="field">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>
    </div>
    
    <div class="field">
        <%= form.label :email, "Email" %>
        <%= form.email_field :email %>
    </div>
    
    <div class="field">
        <%= form.label :password, "Senha" %>
        <%= form.password_field :password %>
    </div>
    
    <div class="field">
        <%= form.label :password_confirmation, "Confirmar senha" %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= form.submit "Cadastrar"%>
    </div>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %> 

app/views/users/new.html.erb
<h1>Cadastre-se!<h1>

<%= render 'form', user: @user %>

<p> <p>

app/views/users/show.html.erb
<br>
nome: <%= @user.name%> <br>
email: <%= @user.email %> <br>
<br>
<br>

<strong> My Posts </strong>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Likes</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
        <%if post.user == @user%>
            <tr>
                <td><%= post.title %></td>
                <td><%= post.content %></td>
                <td><%= post.user.name %></td>
                <td><%= post.likes.length %></td>
                <td><%= link_to 'Show', post %></td>
            </tr>   
        <%end%>
    <% end %>
  </tbody>
</table>
<br>
<br>

<%= link_to "Feed", posts_path %>
<%= link_to "Fazer post", new_post_path %>